START /B python bot.py bot1
START /B python bot.py bot2
START /B python bot.py bot3
START /B python bot.py bot4
START /B python bot.py bot5
START /B python bot.py bot6
START /B python bot.py bot7
START /B python bot.py bot8
START /B python bot.py bot9
START /B python bot.py bot10